name: com.example.simple_flutter_app
description: A simple Flutter application using the Cubit pattern for state management. The app features a login screen and a home screen with logout functionality.
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.7
  mocktail: ^0.2.0

flutter:
  uses-material-design: true